---
- name: Verify
  hosts: rhbk
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Check if keycloak service started
      ansible.builtin.assert:
        that:
          - ansible_facts.services["rhbk.service"]["state"] == "running"
          - ansible_facts.services["rhbk.service"]["status"] == "enabled"

    - name: Set internal envvar
      ansible.builtin.set_fact:
        hera_home: "{{ lookup('env', 'HERA_HOME') }}"

    - name: Verify openid config
      when:
        - hera_home is defined
        - hera_home | length == 0
      block:
        - name: Fetch openID config # noqa blocked_modules command-instead-of-module
          ansible.builtin.shell: |
            set -o pipefail
            curl -H 'Host: rhbk' https://localhost:8443/realms/master/.well-known/openid-configuration -k | jq .
          args:
            executable: /bin/bash
          delegate_to: rhbk1
          register: openid_config
          changed_when: False
        - name: Verify endpoint URLs
          ansible.builtin.assert:
            that:
              - (openid_config.stdout | from_json)["backchannel_authentication_endpoint"] == 'https://rhbk/realms/master/protocol/openid-connect/ext/ciba/auth'
              - (openid_config.stdout | from_json)['issuer'] == 'https://rhbk/realms/master'
              - (openid_config.stdout | from_json)['authorization_endpoint'] == 'https://rhbk/realms/master/protocol/openid-connect/auth'
              - (openid_config.stdout | from_json)['token_endpoint'] == 'https://rhbk/realms/master/protocol/openid-connect/token'
          delegate_to: rhbk1

    - name: Check default log folder
      ansible.builtin.stat:
        path: "/var/log/rhbk"
      register: rhbk_default_log_folder
      failed_when: false

    - name: Check that default rhbk log folder doesn't exist
      ansible.builtin.assert:
        that:
          - rhbk_default_log_folder.stat.exists

    - name: Check default log folder
      ansible.builtin.slurp:
        path: /var/log/rhbk/rhbk.log
      register: rhbk_log
      failed_when: false
