argument_specs:
    main:
        options:
            domain_name:
                # line 14 of aws/defaults/main.yml
                required: true
                description: "The customizable portion of the FQDN assigned to public IP address. This is an explicit setting. If no value is provided, any existing value will be removed on an existing public IP."
                type: "str"
            privatednszone:
                # line 15 of aws/defaults/main.yml
                required: true
                description: "Name of the private DNS zone."
                type: "str"
            ttl:
                # line 35 of aws/defaults/main.yml
                required: true
                description: "The DNS Time-To-Live (TTL), in seconds."
                type: "int"
            relative_name:
                # line 43 of aws/defaults/main.yml
                required: true
                description: "The relative DNS name provided by this Traffic Manager profile."
                type: "str"
            dns_name:
                # line 46 of aws/defaults/main.yml
                required: false
                description: "Name of the public DNS"
                type: "str"
            vpc:
                # line 49 of aws/defaults/main.yml
                required: true
                description: "dict of regions consisting of lists of VPCs to create"
                type: "dict"
            vm:
                # line 91 of aws/defaults/main.yml
                required: true
                description: "Dictionary to get the details of VM created for the intance"
                type: "list"
